// Mocks generated by Mockito 5.4.6 from annotations
// in green_frontend/test/features/groups/presentation/pages/group_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:green_frontend/features/groups/application/assign_quiz_use_case.dart'
    as _i5;
import 'package:green_frontend/features/groups/application/generate_invitation_use_case.dart'
    as _i4;
import 'package:green_frontend/features/groups/application/get_group_leaderboard_use_case.dart'
    as _i3;
import 'package:green_frontend/features/groups/application/get_group_quizzes_use_case.dart'
    as _i2;
import 'package:green_frontend/features/groups/presentation/bloc/group_detail_bloc.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetGroupQuizzesUseCase_0 extends _i1.SmartFake
    implements _i2.GetGroupQuizzesUseCase {
  _FakeGetGroupQuizzesUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetGroupLeaderboardUseCase_1 extends _i1.SmartFake
    implements _i3.GetGroupLeaderboardUseCase {
  _FakeGetGroupLeaderboardUseCase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerateInvitationUseCase_2 extends _i1.SmartFake
    implements _i4.GenerateInvitationUseCase {
  _FakeGenerateInvitationUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAssignQuizUseCase_3 extends _i1.SmartFake
    implements _i5.AssignQuizUseCase {
  _FakeAssignQuizUseCase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupDetailState_4 extends _i1.SmartFake
    implements _i6.GroupDetailState {
  _FakeGroupDetailState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroupDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupDetailBloc extends _i1.Mock implements _i6.GroupDetailBloc {
  MockGroupDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetGroupQuizzesUseCase get getGroupQuizzes => (super.noSuchMethod(
        Invocation.getter(#getGroupQuizzes),
        returnValue: _FakeGetGroupQuizzesUseCase_0(
          this,
          Invocation.getter(#getGroupQuizzes),
        ),
      ) as _i2.GetGroupQuizzesUseCase);

  @override
  _i3.GetGroupLeaderboardUseCase get getGroupLeaderboard => (super.noSuchMethod(
        Invocation.getter(#getGroupLeaderboard),
        returnValue: _FakeGetGroupLeaderboardUseCase_1(
          this,
          Invocation.getter(#getGroupLeaderboard),
        ),
      ) as _i3.GetGroupLeaderboardUseCase);

  @override
  _i4.GenerateInvitationUseCase get generateInvite => (super.noSuchMethod(
        Invocation.getter(#generateInvite),
        returnValue: _FakeGenerateInvitationUseCase_2(
          this,
          Invocation.getter(#generateInvite),
        ),
      ) as _i4.GenerateInvitationUseCase);

  @override
  _i5.AssignQuizUseCase get assignQuiz => (super.noSuchMethod(
        Invocation.getter(#assignQuiz),
        returnValue: _FakeAssignQuizUseCase_3(
          this,
          Invocation.getter(#assignQuiz),
        ),
      ) as _i5.AssignQuizUseCase);

  @override
  _i6.GroupDetailState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGroupDetailState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.GroupDetailState);

  @override
  _i7.Stream<_i6.GroupDetailState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i6.GroupDetailState>.empty(),
      ) as _i7.Stream<_i6.GroupDetailState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i6.GroupDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.GroupDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.GroupDetailState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.GroupDetailEvent>(
    _i8.EventHandler<E, _i6.GroupDetailState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i8.Transition<_i6.GroupDetailEvent, _i6.GroupDetailState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void onChange(_i8.Change<_i6.GroupDetailState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
